# Generated by Django 4.0.4 on 2022-11-15 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('grievanceID', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('grievantType', models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('staff', 'Staff')], max_length=20)),
                ('category', models.CharField(choices=[('Student', (('academic', 'Teaching-Learning and Evaluation'), ('registration', 'Registration, Fees, Results and Transcripts'), ('placement', 'Internships and Placement'), ('general', 'General Amenities and Services'), ('stud2stud', 'Student to Student Grievances'))), ('Faculty/Staff', (('hra', 'Human Resource and Administration'), ('facultyAction', 'Matters related to an Action of any Member of the Faculty'), ('staffAction', 'Matters related to an Action of any Member of the Staff'), ('service', 'Matters related to Service Conditions')))], max_length=20)),
                ('level', models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3')], default=1)),
                ('status', models.IntegerField(choices=[(0, 'In Progress'), (1, 'Solved'), (-1, 'Rejected')], default=0)),
                ('created', models.DateTimeField()),
                ('subject', models.CharField(max_length=256)),
                ('level2', models.DateTimeField(blank=True, null=True)),
                ('level3', models.DateTimeField(blank=True, null=True)),
                ('solved', models.DateTimeField(blank=True, null=True)),
                ('rejected', models.DateTimeField(blank=True, null=True)),
                ('response', models.DateTimeField(null=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('updateID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('grievanceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GrievanceRedressalSystemApp.grievance')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Handler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grievantType', models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('staff', 'Staff')], max_length=20)),
                ('category', models.CharField(choices=[('Student', (('academic', 'Teaching-Learning and Evaluation'), ('registration', 'Registration, Fees, Results and Transcripts'), ('placement', 'Internships and Placement'), ('general', 'General Amenities and Services'), ('stud2stud', 'Student to Student Grievances'))), ('Faculty/Staff', (('hra', 'Human Resource and Administration'), ('facultyAction', 'Matters related to an Action of any Member of the Faculty'), ('staffAction', 'Matters related to an Action of any Member of the Staff'), ('service', 'Matters related to Service Conditions')))], max_length=20)),
                ('level', models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3')], default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Grievant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uType', models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('staff', 'Staff')], max_length=20)),
                ('program', models.CharField(blank=True, choices=[('UG', 'UG'), ('PG', 'PG'), ('PHD', 'PHD')], max_length=3)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='grievance',
            name='grievant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GrievanceRedressalSystemApp.grievant'),
        ),
    ]
